# Generated by Django 5.1.6 on 2025-02-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcycledProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Earrings', max_length=255)),
                ('category', models.CharField(default='Metal', max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_status', models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold Out'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('artisan_name', models.CharField(max_length=255)),
                ('artisan_contact_info', models.CharField(max_length=255)),
                ('approval_status', models.BooleanField(default=False)),
                ('stock_availability', models.IntegerField()),
                ('product_images', models.ImageField(blank=True, null=True, upload_to='upcycled_products/')),
                ('location', models.CharField(default='Dhaka', max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trashitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trashitem',
            name='name',
        ),
        migrations.AddField(
            model_name='trashitem',
            name='category',
            field=models.CharField(default='Plastic', max_length=100),
        ),
        migrations.AddField(
            model_name='trashitem',
            name='condition',
            field=models.CharField(default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='trashitem',
            name='delivery_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('packed', 'Packed'), ('on_the_way', 'On its way'), ('delivered', 'Delivered')], default='ready', max_length=20),
        ),
        migrations.AddField(
            model_name='trashitem',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='waste_images/'),
        ),
        migrations.AddField(
            model_name='trashitem',
            name='location',
            field=models.CharField(default='Dhaka', max_length=255),
        ),
        migrations.AddField(
            model_name='trashitem',
            name='material_name',
            field=models.CharField(default='Plastic bottles', max_length=255),
        ),
        migrations.AddField(
            model_name='trashitem',
            name='product_status',
            field=models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold Out'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='trashitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trashitem',
            name='trash_point',
            field=models.CharField(default='Dhanmondi', max_length=255),
        ),
    ]
