# Generated by Django 5.1.6 on 2025-02-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_upcycledproduct_remove_trashitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashitem',
            name='category',
            field=models.CharField(default='Enter category', max_length=100),
        ),
        migrations.AlterField(
            model_name='trashitem',
            name='location',
            field=models.CharField(default='Enter location', max_length=255),
        ),
        migrations.AlterField(
            model_name='trashitem',
            name='material_name',
            field=models.CharField(default='Enter material name', max_length=255),
        ),
        migrations.AlterField(
            model_name='trashitem',
            name='trash_point',
            field=models.CharField(default='Enter trashpoint location', max_length=255),
        ),
        migrations.AlterField(
            model_name='upcycledproduct',
            name='category',
            field=models.CharField(default='Enter category', max_length=100),
        ),
        migrations.AlterField(
            model_name='upcycledproduct',
            name='location',
            field=models.CharField(default='Enter location', max_length=255),
        ),
        migrations.AlterField(
            model_name='upcycledproduct',
            name='product_name',
            field=models.CharField(default='Enter product name', max_length=255),
        ),
    ]
