# Generated by Django 5.1.6 on 2025-02-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_trashitem_category_alter_trashitem_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashitem',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trashitem',
            name='condition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trashitem',
            name='delivery_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('packed', 'Packed'), ('on_the_way', 'On its way'), ('delivered', 'Delivered')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trashitem',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trashitem',
            name='material_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trashitem',
            name='product_status',
            field=models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold Out'), ('inactive', 'Inactive')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trashitem',
            name='trash_point',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='upcycledproduct',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='upcycledproduct',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='upcycledproduct',
            name='product_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='upcycledproduct',
            name='product_status',
            field=models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold Out'), ('inactive', 'Inactive')], default='', max_length=20),
        ),
    ]
