# Generated by Django 5.1.5 on 2025-03-11 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_trashitem_category_alter_trashitem_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcycledproduct',
            name='listing_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
